### ISSUE TITLE
Failed to load weights

### ISSUE THREAD

**Issue by maroacc** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#1]
Hello,

I have just cloned the github repository and was trying to check that it works by predicting the test/test.mp4 video. I am running the predict.py script like so:

`%run predict.py --HEIGHT 720 --WIDTH 1280`

However, I get the following error:

`Fail to load weights, please modify path in parser.py --load_weights
Load csv file successfully`

I have tried modifzing the parse.py file to try one of the two files that are in the weights folder (weights/TrackNet_final.index and weights/TrackNet_final.data-00000-of-00001), since the one by default (weights/TrackNet) does not exist. 

Is there anything I am doing wrong?

Thank you for your help

**Comment by Chang-Chia-Chi** [comment]
I've correct the name of two files. Please try it again.
(Use original setting "weights/TrackNet" in parser.py)
If any question raised further, please let me know, Thanks.

Regards,
Max

**Comment by Chang-Chia-Chi** [comment]
Closed the issue.
