### ISSUE TITLE
Possible bug in video2img.py

### ISSUE THREAD

**Issue by YannickGibson** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#15]
The test data provided denotes x and y values in the range of 0 to 1. I use this value in video2img.py to generate heatmaps. 

But in the repository there might be a bug since i think it should be done like this `cx = int(x_percentage * WIDTH)` analogously with cy. 
In the current code it is like this `cx = int(x_percentage / ratio)`, where ratio is `image.shape[0] / height`.

Is it possible to fix the issue in the repo?

https://github.com/Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2/blob/03adad1e4d6e3df0303346b684744504abf52e0f/video2img.py#L47

**Comment by Chang-Chia-Chi** [comment]
I reviewed the formula used in the codebase and it appears to be correct. Here’s the breakdown:

Given:
- The original height of the video: `H2`
- The target height: `HEIGHT = H1`
- The height of the ball in the video: `Y`
- The y_percentage is calculated as `Y / H2`.

When adjusting for the target height, the formula becomes:
`y_percentage * HEIGHT = (Y / H2) * H1 = Y / ratio`.

Therefore, even though it might not be immediately obvious, the formula used in the codebase should be correct.

If you have any concerns or further questions, feel free to discuss them.

**Comment by YannickGibson** [comment]
You are correct about this

`Y / (H2/H1) == (Y / H2) * H1`
see:
for Y=0.5, H2=20, H1=10
`0.5 / (20/10) = 0.5 / 2 = 0.25`
`(0.5 / 20) * 10 =  0.025 * 10 = 0.25`

But my understanding is, that I instead, should gain value 5, because y is in the middle of the image (0 to 10). 
In my example i get:
`y_percentage * HEIGHT = 0.5 * 10 = 5` (which gives you the correct pixel position)

There is also pixel conversion that i dont want to get into, that would floor the value 0.25 to 0 which just outputs every heatmap with balls in the top left corner.

Edit:
I think you are mistaking what is the Y value. It is not the integer pixel position of the ball, but rather its percentage (Y = y_percentage). If you check the code, it is loaded from `test.csv` directly, which indeed contains percentages.
https://github.com/Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2/blob/03adad1e4d6e3df0303346b684744504abf52e0f/video2img.py#L30
https://github.com/Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2/blob/03adad1e4d6e3df0303346b684744504abf52e0f/test/test.csv#L2

**Comment by Chang-Chia-Chi** [comment]
I found I was wrong and corrected the code in commit [`2521155`](https://github.com/Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2/commit/2521155784833ba6326febc7acaac3892682946d).
