### ISSUE TITLE
Failed to load Weights part II

### ISSUE THREAD

**Issue by maroacc** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#2]
Sorry for the late reply,

I re-cloned the repository with the update of the files and it still does not work. It does retrieve correctly the test/test.csv file, so I do not think this issue is related to correctly writting the path. However, I include a screenshot of my structure just in case: 

![image](https://user-images.githubusercontent.com/45521548/111440774-f67ef100-8706-11eb-9c10-b377df7c85d1.png)

Thank you for your help,
María José

**Comment by Chang-Chia-Chi** [comment]
Sorry for late response, I'm quite busy recently.
Could you paste error message so I might figure out what goes wrong, Thanks!

Regards,
Max

**Comment by maroacc** [comment]
These are all the commands that I have been executing:

![image](https://user-images.githubusercontent.com/45521548/111757354-88b7fe00-889b-11eb-8339-53dff9f06044.png)

I get this error while it is executing the last one:

![image](https://user-images.githubusercontent.com/45521548/111756764-ded87180-889a-11eb-91e9-a30d2219e975.png)
It does not go anywhere from there, but if I stop the execution it gives this error:

Fail to load weights, please modify path in parser.py --load_weights
Load csv file successfully
Beginning predicting......
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/content/TrackNet-Badminton-Tracking-tensorflow2/predict.py in <module>()
    112 
    113         start = time.time()
--> 114         y_pred = model.predict(img_input, batch_size=BATCH_SIZE)
    115         end = time.time()
    116         time_list.append(end-start)

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1627           for step in data_handler.steps():
   1628             callbacks.on_predict_batch_begin(step)
-> 1629             tmp_batch_outputs = self.predict_function(iterator)
   1630             if data_handler.should_sync:
   1631               context.async_wait()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    853       # In this case we have created variables on the first call, so we run the
    854       # defunned version which is guaranteed to never create variables.
--> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    856     elif self._stateful_fn is not None:
    857       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
-> 2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 
   2945   @property

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

KeyboardInterrupt: 

Thank you for your time,
María

**Comment by eddymina** [comment]
The weights are missing the pb file/are not in the proper format. They may have been to large to upload to github. Any chance you have the complete pretrained weights?

**Comment by Gi-gigi** [comment]
> I re-cloned the repository with the update of the files and it still does not work. It does retrieve correctly the test/test.csv file, so I do not think this issue is related to correctly writting the path. However, I include a screenshot of my structure just in case:

I have met some similar question, I can't "python predict.py "

`Traceback (most recent call last):
  File "/user/TrackNet-Badminton-Tracking-tensorflow2-main/predict.py", line 125, in <module>
    tp, tn, fp1, fp2, fn = confusion(y_pred, y_true, tol)
  File "/user/TrackNet-Badminton-Tracking-tensorflow2-main/utils.py", line 189, in confusion
    _, contours, _ = cv2.findContours(h_pred[0].copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)`

I do't why become this problem, my --video_path and --label_path is correct.

**Comment by francoyeung** [comment]
> > 我使用文件更新重新克隆了存储库，但它仍然无法正常工作。它确实正确检索了 test/test.csv 文件，所以我认为这个问题与正确写入路径无关。但是，为了以防万一，我包含了我的结构的屏幕截图：
> 
> 我遇到了一些类似的问题，我不能“python predict.py”
> 
> `Traceback (most recent call last): File "/user/TrackNet-Badminton-Tracking-tensorflow2-main/predict.py", line 125, in <module> tp, tn, fp1, fp2, fn = confusion(y_pred, y_true, tol) File "/user/TrackNet-Badminton-Tracking-tensorflow2-main/utils.py", line 189, in confusion _, contours, _ = cv2.findContours(h_pred[0].copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) ValueError: not enough values to unpack (expected 3, got 2)`
> 
> 我不为什么会成为这个问题，我的 --video_path 和 --label_path 是正确的。

You need to change the output of cv2.findContours, because it has changed.
`_, contours, _ = cv2.findContours(h_pred[0].copy(), cv2.RETR_EXTERNAL`
to
`contours, _ = cv2.findContours(h_pred[0].copy(), cv2.RETR_EXTERNAL`

BTW, can I communicate with you personally? cause I am working on it right now. My wechat is FrancoYeung_
