### ISSUE TITLE
Speeding up training by multi GPUs ?

### ISSUE THREAD

**Issue by sisrfeng** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#7]
Hi, have you tried training on multi GPUs?  
I struggled with the author's codes:  
```https://nol.cs.nctu.edu.tw:234/open-source/TrackNetv2```
but even after training for 10 epochs, the model can not predict any positive example.  
```
        with tf.device('/cpu:0'):
       ┊   model=TrackNet(HEIGHT, WIDTH)
       model_on_gpus = multi_gpu_model(model, gpus=len(gpu_list))
```

And the new pytorch version seems can only train on single gpu.
Do you know the reason ?

The author has not reply me and my time has limited to finish my project, so I look forward to your reply.  
Thx!

**Comment by Chang-Chia-Chi** [comment]
Sorry I haven't tried before with multi-gpu training.

**Comment by Gi-gigi** [comment]
> https://nol.cs.nctu.edu.tw:234/open-source/TrackNetv2

this project is only version about tensorflow, no pythorch. and I think there are  too some questions for it to run this project.

**Comment by sisrfeng** [comment]
The official pytorch version can not train with mutil GPUs, either

**Comment by Gi-gigi** [comment]
> 

do u have any Contact information that i can talk with u, like qq?

**Comment by sisrfeng** [comment]
584400706@qq.com
